const COMPANIES = {
  ABT: 'ABT',
  ACB: 'ACB',
  AST: 'AST',
  BIC: 'BIC',
  BSR: 'BSR',
  CDN: 'CDN',
  DCM: 'DCM',
  DGC: 'DGC',
  DHC: 'DHC',
  DNW: 'DNW',
  DRI: 'DRI',
  HHP: 'HHP',
  GEG: 'GEG',
  GHC: 'GHC',
  HNF: 'HNF',
  HPG: 'HPG',
  KHS: 'KHS',
  NCS: 'NCS',
  NTC: 'NTC',
  NNC: 'NNC',
  PAT: 'PAT',
  PPH: 'PPH',
  PVI: 'PVI',
  PVP: 'PVP',
  SAS: 'SAS',
  SGC: 'SGC',
  SGN: 'SGN',
  SHB: 'SHB',
  SP2: 'SP2',
  TVT: 'TVT',
  TYA: 'TYA',
  VNR: 'VNR',
  VSC: 'VSC',
  MBB: 'MBB',
  ANV: 'ANV',
  PHP: 'PHP'
};

export { COMPANIES };