jobs:
  run-each-script:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3 # <== CHỈNH SỐ NÀY TÙY Ý (3-5 là hợp lý)
      matrix:
        script:
          - bctc-abt.js
          - bctc-acb.js
          - bctc-ast.js
          - bctc-bsr.js
          - bctc-cdn.js
          - bctc-dcm.js
          - bctc-dgc.js
          - bctc-dhc.js
          - bctc-dnw.js
          - bctc-dri.js
          - bctc-geg.js
          - bctc-ghc.js
          - bctc-hhp.js
          - bctc-hpg.js
          - bctc-khs.js
          - bctc-ncs.js
          - bctc-nnc.js
          - bctc-ntc.js
          - bctc-pat.js
          - bctc-pph.js
          - bctc-pvp.js
          - bctc-sgn.js
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run ${{ matrix.script }}
        run: node ${{ matrix.script }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
